-- ─────────────────────────────────────────────────────────────────
-- Project screenshots: gallery table, storage bucket, and closing the
-- anonymous write hole on projects
-- ─────────────────────────────────────────────────────────────────

-- 1 ── Close the public write hole on projects
--     All three write policies were granted to {public}. The anon key that
--     ships in the browser bundle could therefore insert, rewrite or delete
--     any project, and the public SELECT policies made every row readable
--     while doing it. Public reads stay, since the portfolio is public by
--     design; writes become admin-only.
DROP POLICY IF EXISTS "Admin can insert projects" ON projects;
DROP POLICY IF EXISTS "Admin can update projects" ON projects;
DROP POLICY IF EXISTS "Admin can delete projects" ON projects;

CREATE POLICY "Admins can insert projects"
  ON projects FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

CREATE POLICY "Admins can update projects"
  ON projects FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

CREATE POLICY "Admins can delete projects"
  ON projects FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

-- 2 ── Gallery table
--     projects.image_url stays as the single cover thumbnail that
--     ProjectsPage already renders. Screenshots go here so a project can
--     hold many, in a deliberate order, with an optional caption.
--     ON DELETE CASCADE so removing a project clears its screenshots.
CREATE TABLE IF NOT EXISTS project_images (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  bigint NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  image_url   text NOT NULL,
  caption     text,
  sort_order  integer NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_project_images_project
  ON project_images(project_id, sort_order);

ALTER TABLE project_images ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view project images" ON project_images;
DROP POLICY IF EXISTS "Admins can add project images" ON project_images;
DROP POLICY IF EXISTS "Admins can update project images" ON project_images;
DROP POLICY IF EXISTS "Admins can delete project images" ON project_images;

-- The gallery is shown on the public project page.
CREATE POLICY "Anyone can view project images"
  ON project_images FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Admins can add project images"
  ON project_images FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

CREATE POLICY "Admins can update project images"
  ON project_images FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

CREATE POLICY "Admins can delete project images"
  ON project_images FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

-- 3 ── Storage bucket for uploaded screenshots
--     Public bucket so the URLs can be used in a plain <img src>, with
--     upload/update/delete restricted to admins.
INSERT INTO storage.buckets (id, name, public)
VALUES ('project-images', 'project-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Allow public to view project images" ON storage.objects;
DROP POLICY IF EXISTS "Allow admin to upload project images" ON storage.objects;
DROP POLICY IF EXISTS "Allow admin to update project images" ON storage.objects;
DROP POLICY IF EXISTS "Allow admin to delete project images" ON storage.objects;

CREATE POLICY "Allow public to view project images"
  ON storage.objects FOR SELECT TO public
  USING (bucket_id = 'project-images');

CREATE POLICY "Allow admin to upload project images"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'project-images'
    AND EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

CREATE POLICY "Allow admin to update project images"
  ON storage.objects FOR UPDATE TO authenticated
  USING (
    bucket_id = 'project-images'
    AND EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

CREATE POLICY "Allow admin to delete project images"
  ON storage.objects FOR DELETE TO authenticated
  USING (
    bucket_id = 'project-images'
    AND EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );